# Generated by Django 4.1.4 on 2022-12-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='points',
            field=models.IntegerField(default=1),
        ),
    ]
