# Generated by Django 4.1.4 on 2023-01-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='break_time',
        ),
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
        migrations.AddField(
            model_name='review',
            name='completed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='scheduled',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='started',
            field=models.DateTimeField(null=True),
        ),
    ]
