# Generated by Django 4.1.4 on 2023-01-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_alter_review_completed_alter_review_scheduled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
