# Generated by Django 4.1.4 on 2023-01-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_alter_review_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
